[toolchain]
profile = "minimal"
# channel = "nightly-2024-05-02"
channel = "nightly-2024-09-04"
# channel = "nightly-2024-10-15"
# channel = "nightly-2024-08-01"
# channel = "nightly-2024-07-01"
components = ["rust-src", "llvm-tools", "rustfmt", "clippy"]
targets = ["x86_64-unknown-none", "riscv64gc-unknown-none-elf", "aarch64-unknown-none", "aarch64-unknown-none-softfloat"]
